### PR TITLE
docs page for Nodes

### PR DESCRIPTION
**Pull request by savitakartik**
WIP

### CODE REVIEW

**Comment by savitakartik** [comment]
WIP

**Comment by benjeffery** [comment]
@savitakartik I've added some placeholder content for the other pages

**Comment by benjeffery** [comment]
@savitakartik Going to merge this so we can release - feel free to open PRs if you want to add anything.

**Comment by savitakartik** [comment]
Ah I just got back to working on this PR after my poster but I'm fine to merge.

**Pull request merged**
