### PR TITLE
Sidebar controls - WIP

### PR DESCRIPTION
**Pull request by benjeffery**
After some iteration, here's what I've landed on for the refactor of pages. Each page is now a class with a sidebar method and main content. The main content function then uses `param.depends` for the reactivity.
I've only done overview, mutations and edge-explorer for now.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Can you post a screenshot so we can see please?

**Comment by benjeffery** [comment]
Screenshot from 2024-09-18 11-48-49

**Comment by jeromekelleher** [comment]
Nice, looks great on all counts

**Comment by benjeffery** [comment]
Realised a much simpler and performant way to do this, which is now in this PR - each page class has state and we just return that state on each switch rather than recreate the page each time.

TODO

- [ ] Reinstate error handling
- [ ] Reinstate raster
- [ ] Reinstate loading

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Pull request merged**
