### PR TITLE
Raster CLI

### LINKED ISSUE #161: CLI for raster generation
Something like `tsqc screenshot [page-id] [width] [height] outfile.png`

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #161 

Add a `tsbrowse screenshot` command to generate a PNG of a specific page.

### CODE REVIEW

**Review by jeromekelleher — COMMENTED** [review]
Can't see the raster.py file?

**Comment by jeromekelleher** [comment]
Looks like file is missing, and not clear how tests are passing then?

**Comment by savitakartik** [comment]
I couldn't test this on UKB trees as it's been a challenge to install the webdriver for Selenium on the cluster, but it works well on other inferred trees I have. The histograms show up nicely, but the interactive plots don't show up. I think this may be a separate issue with datashaded plots though, as the main mutations/edges/nodes plots don't render properly even when I do `tsbrowse serve`. I'll create an issue. 
image

**Comment by benjeffery** [comment]
@jeromekelleher `raster.py` was already on `main`.

I've added the `-o` in https://github.com/tskit-dev/tsbrowse/pull/173/commits/487ec7bcc7dbdecb5c605f93642f8136609fe88c (I also added this to `preprocess`)

**Comment by benjeffery** [comment]
@savitakartik I'm also getting the bug of mutations not appearing until I pan/zoom the plot.

**Review by jeromekelleher — APPROVED** [review]

**Pull request merged**
